APP_ENV = "development" unless defined? APP_ENV
$:.push(File.join(File.dirname(__FILE__)))
require 'yaml'
require 'logger'
require 'logger_facade'
require 'utility'
require 'settings'
require 'slimtimer4r'
require 'task_manager'
require 'slim_timer_methods'
require 'validation'
require 'action'
require 'start_action'
require 'stop_action'
require 'complete_action'
require 'create_action'
require 'show_action'
require 'configure_action'
require 'main_action'
